//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoltageMonitor.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Telemetry
    {
        public int Id { get; set; }
        public System.DateTime Sample_Time { get; set; }
        public double Voltage { get; set; }
        public string Device_ID { get; set; }
        public string Device_Channel { get; set; }
    }
}
